name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /var/www/aibot/
          git pull origin main
          git status
          cd /var/www/aibot/aibot
          python3 -m venv botvenv
          source /var/www/aibot/aibot/botvenv/bin/activate
          python -m pip install -r requirements.txt
          
          # Install nvm and use it to install Node.js version 20
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
          if [ ! -d "$NVM_DIR" ]; then
            echo "Installing nvm..."
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # Load nvm
          fi
          
          echo "Installing Node.js version 20..."
          nvm install 20
          nvm use 20
          
          # Confirm Node.js and npm versions
          node -v
          npm -v

          cd /var/www/aibot/voice_synth
          
          # Install dependencies, including dev dependencies
          npm install
          
          # Check if vite is installed
          if ! command -v vite &> /dev/null
          then
              echo "vite not found, installing..."
              npm install vite --save-dev
          fi

          # Run build
          npm run build
